name: heatmap-aggregator
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream-group-by-page
    required: true
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: heatmap
    required: true
  - name: grid_size
    inputType: FreeText
    defaultValue: 50
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
