name: StarCounter
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: kafka-python-deps
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: stars
    required: false
  - name: gh_token
    inputType: Secret
    description: ''
    defaultValue: gh_token
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
